# Generated by Django 5.2.4 on 2025-09-03 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curtains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Buyurtma raqami')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlandi'), ('in_progress', 'Tayyorlanmoqda'), ('ready', 'Tayyor'), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20, verbose_name='Holati')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Mijoz ismi')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('customer_address', models.TextField(verbose_name='Manzil')),
                ('notes', models.TextField(blank=True, help_text="Mijoz tomonidan qoldirilgan qo'shimcha ma'lumotlar", verbose_name="Qo'shimcha ma'lumot")),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('confirmed_date', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan qaralgan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'db_table': 'orders_order',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miqdori')),
                ('unit_price', models.PositiveIntegerField(help_text='Buyurtma berish vaqtidagi narx', verbose_name='Birlik narxi')),
                ('custom_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maxsus eni (sm)')),
                ('custom_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maxsus balandligi (sm)')),
                ('custom_notes', models.TextField(blank=True, verbose_name='Maxsus talablar')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqt")),
                ('curtain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curtains.curtain', verbose_name='Parda')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Buyurtma elementi',
                'verbose_name_plural': 'Buyurtma elementlari',
                'db_table': 'orders_order_item',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlandi'), ('in_progress', 'Tayyorlanmoqda'), ('ready', 'Tayyor'), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilindi')], max_length=20, verbose_name='Oldingi holat')),
                ('new_status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlandi'), ('in_progress', 'Tayyorlanmoqda'), ('ready', 'Tayyor'), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilindi')], max_length=20, verbose_name='Yangi holat')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name="O'zgartirilgan vaqt")),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirgan")),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Buyurtma holati tarixi',
                'verbose_name_plural': 'Buyurtma holati tarixi',
                'db_table': 'orders_status_history',
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_date'], name='orders_orde_status_bd89a8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_phone'], name='orders_orde_custome_59f5e1_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'curtain')},
        ),
    ]
