# Generated by Django 5.2.4 on 2025-09-02 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Kategoriya nomi', max_length=225, verbose_name='Nomi')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'db_table': 'categories',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Rang nomi', max_length=225, verbose_name='Rang nomi')),
                ('hex_code', models.CharField(blank=True, help_text='#ffffff formatida', max_length=7, null=True, verbose_name='Rang kodi')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Rang',
                'verbose_name_plural': 'Ranglar',
                'db_table': 'colors',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Curtain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Parda nomi', max_length=225, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('content', models.TextField(blank=True, help_text="Parda haqida batafsil ma'lumot", null=True, verbose_name="Ta'rif")),
                ('price', models.PositiveIntegerField(help_text="So'mda narx", verbose_name='Narxi')),
                ('discount_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Chegirmali narx')),
                ('fabric_type', models.CharField(choices=[('cotton', 'Paxta'), ('silk', 'Ipak'), ('linen', "Zig'ir"), ('polyester', 'Polyester'), ('velvet', 'Baxmal'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Mato turi')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Eni (sm)')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Balandligi (sm)')),
                ('status', models.CharField(choices=[('available', 'Mavjud'), ('out_of_stock', 'Tugagan'), ('discontinued', "To'xtatilgan")], default='available', max_length=20, verbose_name='Holati')),
                ('is_featured', models.BooleanField(default=False, help_text="Asosiy sahifada ko'rsatish", verbose_name='Asosiy')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Ombordagi soni')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curtains', to='curtains.category', verbose_name='Kategoriya')),
                ('colors', models.ManyToManyField(blank=True, related_name='curtains', to='curtains.color', verbose_name='Ranglar')),
            ],
            options={
                'verbose_name': 'Parda',
                'verbose_name_plural': 'Pardalar',
                'db_table': 'curtains',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='CurtainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='curtains/%Y/%m/%d/', verbose_name='Rasm')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt matni')),
                ('is_main', models.BooleanField(default=False, verbose_name='Asosiy rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('curtain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='curtains.curtain', verbose_name='Parda')),
            ],
            options={
                'verbose_name': 'Parda rasmi',
                'verbose_name_plural': 'Parda rasmlari',
                'db_table': 'curtain_images',
                'ordering': ['order', '-created_date'],
            },
        ),
        migrations.AddIndex(
            model_name='curtain',
            index=models.Index(fields=['slug'], name='curtains_slug_a8be48_idx'),
        ),
        migrations.AddIndex(
            model_name='curtain',
            index=models.Index(fields=['category', 'is_active'], name='curtains_categor_dc1357_idx'),
        ),
        migrations.AddIndex(
            model_name='curtain',
            index=models.Index(fields=['is_featured', 'is_active'], name='curtains_is_feat_7d8eda_idx'),
        ),
    ]
